"""LaTeX macro generation from summary data.

Generates macros.tex with \\providecommand for every model-task metric,
eliminating hardcoded values in the LaTeX paper.
"""

from __future__ import annotations

import os

from scripts.analysis.config import TASK_DISPLAY_NAMES


# ---------------------------------------------------------------------------
# Model key -> LaTeX command name fragment
# ---------------------------------------------------------------------------

LATEX_NAMES: dict[str, str] = {
    "sozkz-50m": "SozKZFiftyM",
    "sozkz-150m": "SozKZOneFiftyM",
    "sozkz-300m": "SozKZThreeHundredM",
    "sozkz-600m": "SozKZSixHundredM",
    "gemma-2b": "GemmaTwoB",
    "gemma-9b": "GemmaNineB",
    "llama-3-1b": "LlamaThreeOneB",
    "llama-3-3b": "LlamaThreeThreeB",
    "llama-3-8b": "LlamaThreeEightB",
    "qwen-0.5b": "QwenZeroFiveB",
    "qwen-1.5b": "QwenOneFiveB",
    "qwen-7b": "QwenSevenB",
    "mistral-7b": "MistralSevenB",
    "gpt-oss-120b": "GptOssOneTwentyB",
}


def model_key_to_latex(model_key: str) -> str:
    """Convert model key to valid LaTeX command name fragment.

    Args:
        model_key: Model identifier (e.g., "sozkz-600m").

    Returns:
        CamelCase LaTeX-safe name (e.g., "SozKZSixHundredM").

    Raises:
        KeyError: If model_key is not in LATEX_NAMES.
    """
    return LATEX_NAMES[model_key]


def _task_to_latex(task: str) -> str:
    """Convert task name to CamelCase for LaTeX command name."""
    mapping = {
        "bpb": "Bpb",
        "mc_qa": "McQa",
        "sentiment": "Sentiment",
        "belebele": "Belebele",
        "ner": "Ner",
        "sib200": "SibTwoHundred",
    }
    return mapping.get(task, task.title())


def generate_macros(
    summary: dict, output_path: str = "paper/macros.tex"
) -> str:
    """Generate macros.tex with \\providecommand for every model-task metric.

    Args:
        summary: Parsed summary.json dict with "models" key.
        output_path: Path for output .tex file.

    Returns:
        Path to saved .tex file.
    """
    lines: list[str] = [
        "% Auto-generated by scripts/analysis/generate_all.py",
        "% DO NOT EDIT MANUALLY -- regenerate with: python scripts/analysis/generate_all.py",
        "",
    ]

    models_data = summary["models"]

    # Count macros
    num_models = len(models_data)
    num_tasks = len(summary.get("tasks", []))

    # Model count and task count macros
    lines.append(f"\\providecommand{{\\numModels}}{{{num_models}}}")
    lines.append(f"\\providecommand{{\\numTasks}}{{{num_tasks}}}")
    lines.append("")

    # Per-model per-task macros
    for model_key in sorted(models_data.keys()):
        if model_key not in LATEX_NAMES:
            continue
        latex_name = LATEX_NAMES[model_key]
        model_scores = models_data[model_key]

        for task, value in sorted(model_scores.items()):
            if value is None:
                continue
            task_latex = _task_to_latex(task)

            if task == "bpb":
                # BPB: raw value with 3 decimal places
                cmd_name = f"bpb{latex_name}"
                formatted = f"{value:.3f}"
            else:
                # Accuracy: percentage with 1 decimal place + \%
                cmd_name = f"acc{task_latex}{latex_name}"
                formatted = f"{value * 100:.1f}\\%"

            lines.append(f"\\providecommand{{\\{cmd_name}}}{{{formatted}}}")

        lines.append("")  # Blank line between models

    content = "\n".join(lines)

    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    return output_path
