"""LaTeX comparison table generation for model evaluation results.

Generates a publication-ready LaTeX table with booktabs formatting,
bold best values, and proper number formatting.
"""

from __future__ import annotations

import os

import pandas as pd

from scripts.analysis.config import (
    MODEL_ORDER,
    PARAM_SIZES,
    TASKS,
    TASK_DISPLAY_NAMES,
    setup_academic_style,
)


def generate_comparison_table(
    summary: dict, output_dir: str = "paper/tables"
) -> str:
    """Generate LaTeX comparison table from summary data.

    Rows = models (ordered by MODEL_ORDER), columns = tasks.
    Bold the best value in each column (lowest for BPB, highest for accuracy).

    Args:
        summary: Parsed summary.json dict with "models" key.
        output_dir: Directory to save output files.

    Returns:
        Path to saved TeX file.
    """
    setup_academic_style()

    models_data = summary["models"]

    # Filter to models present in summary, ordered by MODEL_ORDER
    ordered_models = [m for m in MODEL_ORDER if m in models_data]

    if not ordered_models:
        raise ValueError("No models found in summary data")

    # Build raw values matrix for finding best per column
    raw_values: dict[str, dict[str, float | None]] = {}
    for model in ordered_models:
        raw_values[model] = {}
        for task in TASKS:
            raw_values[model][task] = models_data[model].get(task)

    # Find best value per task
    best: dict[str, float | None] = {}
    for task in TASKS:
        vals = [raw_values[m][task] for m in ordered_models if raw_values[m][task] is not None]
        if not vals:
            best[task] = None
        elif task == "bpb":
            best[task] = min(vals)  # lower is better
        else:
            best[task] = max(vals)  # higher is better

    # Format values with bold for best
    def _fmt(model: str, task: str) -> str:
        val = raw_values[model][task]
        if val is None:
            return "--"
        if task == "bpb":
            formatted = f"{val:.3f}"
        else:
            formatted = f"{val * 100:.1f}"

        if best[task] is not None and abs(val - best[task]) < 1e-9:
            return f"\\textbf{{{formatted}}}"
        return formatted

    # Build DataFrame
    rows = []
    for model in ordered_models:
        row = {"Model": model}
        params = PARAM_SIZES.get(model)
        if params is not None:
            if params >= 1000:
                row["Params"] = f"{params / 1000:.0f}B"
            else:
                row["Params"] = f"{params}M"
        else:
            row["Params"] = "--"
        for task in TASKS:
            col_name = TASK_DISPLAY_NAMES.get(task, task)
            row[col_name] = _fmt(model, task)
        rows.append(row)

    df = pd.DataFrame(rows)
    df = df.set_index("Model")

    # Column format: l for index + r for Params + r for each task
    n_cols = 1 + len(TASKS)  # Params + tasks
    col_format = "l" + "r" * n_cols

    # Build booktabs table manually (pandas 3.0 removed booktabs from to_latex)
    cols = list(df.columns)
    lines = ["\\begin{tabular}{" + col_format + "}", "\\toprule"]
    lines.append(" & ".join(["Model"] + cols) + " \\\\")
    lines.append("\\midrule")
    for idx, row in df.iterrows():
        cells = [str(idx)] + [str(row[c]) for c in cols]
        lines.append(" & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    latex = "\n".join(lines) + "\n"

    content = (
        f"% Auto-generated by scripts/analysis/tables.py\n"
        f"% Columns: Model | Params | {' | '.join(TASK_DISPLAY_NAMES[t] for t in TASKS)}\n"
        f"{latex}"
    )

    os.makedirs(output_dir, exist_ok=True)
    tex_path = os.path.join(output_dir, "comparison.tex")
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write(content)

    return tex_path
