[gpu_servers]
kaznu ansible_host=164.138.46.36 ansible_port=15126 ansible_user=root

[gpu_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o ConnectTimeout=120 -o ServerAliveInterval=15'
project_dir=/root/slm

[cloudrift]
ppl_scorer ansible_host=217.138.104.165 ansible_user=riftuser

[cloudrift:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o ConnectTimeout=30 -o ServerAliveInterval=10 -o StrictHostKeyChecking=no'
project_dir=/home/riftuser/slm

[runpod]
translate ansible_host=216.243.220.230 ansible_port=10109 ansible_user=root ansible_ssh_private_key_file=~/.runpod/ssh/RunPod-Key-Go

[runpod:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o ConnectTimeout=30 -o ServerAliveInterval=10 -o StrictHostKeyChecking=no'
