[gpu_servers]
kaznu ansible_host=164.138.46.36 ansible_port=15126 ansible_user=root

[gpu_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o ConnectTimeout=120 -o ServerAliveInterval=15'
project_dir=/root/slm
